#----------------------------------------------
# DO NOT TOUCH THESE UNLESS YOU KNOW WHAT YOU'RE DOING!
debug: false
version: 1.0
#----------------------------------------------

# You can edit from here:

playerShops:
  # Allow teleporting to player shops
  teleport:
    enabled: true
    # Warmup in seconds. Set to 0 to disable.
    warmup: 5
    allowMovement: false

adminShops:
  # Allow teleporting to admin shops
  teleport:
    enabled: true
    # Warmup in seconds. Set to 0 to disable.
    warmup: 5
    # Allow the player to move during countdown
    allowMovement: false
  # Allow remote open admin shops
  remote: false
  filler:
    # The item to use as a filler in the admin shop GUI
    material: GRAY_STAINED_GLASS_PANE

# How often should the shops refresh? (in seconds) keep it above 30 seconds to avoid lag.
refresh-rate: 60

economy:
  # Enable economy support
  enabled: true
  # Set the price limit for trades
  selling-price-limit: 100000000.00
  # Currency Item:
  sell-item:
    # Name format. Use %price% for the price.
    name: "Price: §f$%price%"
    material: GOLD_NUGGET
    glow: true
    lore:
      - "§bClick to edit"
    custom-model-data: 0 # Set to 0 to disable custom model data for the sell item

  # Currency Item:
  buy-item:
    # Name format. Use %price% for the price.
    name: "You get: §f$%price%"
    material: GOLD_NUGGET
    glow: true
    lore:
      - "§bClick to edit"
    custom-model-data: 0 # Set to 0 to disable custom model data for the buy item





# Use '§' for color codes 

messages:
  prefix: "§8[§bShopkeepers Addon§8] §r"
  noMoney: "§cYou don't have enough money to buy this item!"
  noMoneyOwner: "§cThe shop owner doesn't have enough money to sell this item!"
  setPrice: "§aPlease enter the new price for this item:"
  invalidPrice: "§cInvalid price! Please enter a valid number."
  priceChanged: "§aPrice changed successfully!"
  priceChangeCancelled: "§cPrice change cancelled!"
  previousPage:
    title: "§b§lPrevious Page"
  nextPage:
    title: "§b§lNext Page"
  back:
    title: "§b§lBack to Previous Menu"
  homePage:
    title: "§8§lShopkeepers"
    buttons:
      adminShops:
        title: "§bAdmin Shops"
        lore:
          - "§7View all admin shops."
          - "§7Click to open."
      playerShops:
        title: "§bPlayer Shops"
        lore:
          - "§7View all player shops."
          - "§7Click to open."

    # Admin and Player Shops with buttons to navigate to shopkeepers and items
  adminShopsPage:
    title: "§8§lAdmin Shops"
    lore:
      - "§7Here you can view and manage all admin shops."
      - "§7Click on a shop to view its items."
    buttons:
      adminShops:
        title: "§bAdmin Shopkeepers"
        lore:
          - "§7View all admin shopkeepers."
          - "§7Click to open."
      adminItems:
        title: "§bAdmin Items"
        lore:
          - "§7View all items available in admin shops."
          - "§7Click to open."


  playerShopsPage:
    title: "§8§lPlayer Shops"
    lore:
      - "§7Here you can view and manage all player shops."
      - "§7Click on a shop to view its items."
    noShops: "§cNo player shops found."
    buttons:
      playerShops:
        title: "§bPlayer Shopkeepers"
        lore:
          - "§7View all player shopkeepers."
          - "§7Click to open."
      playerItems:
        title: "§bPlayer Items"
        lore:
          - "§7View all items available in player shops."
          - "§7Click to open."

  adminShops:
    title: "§8§lAdmin Shops: %page%" # %page% will be replaced with the current page number
    noRecipe: "§cThis shop has no items or recipes."
    buttons:
      title: "%shop_name%"
      lore:
        - "§c---"
        - "§bLeft-Click to teleport to Admin Shop."
    teleport:
      title: "§cTeleporting...\n§fto Admin Shop"
      subtitle: "§fin §f%time%§f seconds..."
      cancelled: "§cYou moved! Teleportation cancelled!"
      success: "§aTeleported to Admin Shop!"
      noShop: "§cUnable to teleport to Admin Shop or no shop found."
  adminItems:
    title: "§8§lAdmin Items: %page%" # %page% will be replaced with the current page number
    lore:
      - "§7Click to view shops selling this item."

  playerShops:
    title: "§8§lPlayer Shops: %page%"
    buttons:
      title: "%player_name%'s Shop"
      right-click: "§c§lRight-Click to open remote Player Shop."
      left-click: "§b§lLeft-Click to teleport to Player Shop."
      no-shop:
        - "§cThis player has not setup a shop yet."
        - "§cUse §f/setshop §cto setup."
    teleport:
      title: "§cTeleporting...\n§fto Player Shop"
      subtitle: "§fin §f%time%§f seconds..."
      cancelled: "§cYou moved! Teleportation cancelled!"
      success: "§aTeleported to Player Shop!"
      noShop: "§cUnable to teleport to Player Shop or no shop found."
    setShop: "§aShop set successfully! Teleport to your shop using §f/visitShop"

  playerItems:
    title: "§8§lPlayer Items: %page%"
    lore:
      - "§7Click to view shops selling this item."




# -----------------------------------------------
# DO NOT EDIT BELOW THIS LINE UNLESS YOU KNOW WHAT YOU'RE DOING!
# -----------------------------------------------
heads:
  defaultPlayer: "http://textures.minecraft.net/texture/fb0fd60d722419a7857f7286c23f72c21933038fc414049cde656f4e8328e546" # Default player head texture
  previousPage: "http://textures.minecraft.net/texture/da1d55b3f989410a34752650e248c9b6c1783a7ec2aa3fd7787bdc4d0e637d39"
  nextPage: "http://textures.minecraft.net/texture/fa87e3d96e1cfeb9ccfb3ba53a217faf5249e285533b271a2fb284c30dbd9829"
  back: "http://textures.minecraft.net/texture/223fb67429716b21bc6e8e7d669ceddf65b13e0790a5ce55b2e077b82d19e124"


  homePage:
    adminShops: "http://textures.minecraft.net/texture/34ccb52750e97e830aebfa8a21d5da0d364d0fdad9fb0cc220fe2ca8411842c3"
    playerShops: "http://textures.minecraft.net/texture/91be4b5b592fee21a65e0f903038c5333be388234a43731d4adfe5d57d3644e5"
  adminShopsPage:
    adminShops: "http://textures.minecraft.net/texture/71f714133ce78d1181c4d5d3e53711ece10c4c9a28201188ee1a6f35cc0fa3ca"
    adminItems: "http://textures.minecraft.net/texture/854784fb4734784743bf302649fb5700171eaf667861ab2b25ce9aee7a138160"
  playerShopsPage:
    playerShops: "http://textures.minecraft.net/texture/a8cddcff440e2792d9914e1dd117fa82bd859b29ed39ddde345354386b02b776"
    playerItems: "http://textures.minecraft.net/texture/854784fb4734784743bf302649fb5700171eaf667861ab2b25ce9aee7a138160"
  adminShops:
    Shops: "http://textures.minecraft.net/texture/5ccf9ea1a6e1b86ad60a804ff800b0dfd76d73e5c91f47f84bb7169306546012" # Default Villager skin